### ISSUE TITLE
bot无反应

### ISSUE THREAD

**Issue by XT-G3** [joeyHXD/ai#1]
装好之后bot无反应，请问下是什么个情况？要如何解决
![QQ截图20221014233420](https://user-images.githubusercontent.com/111116375/195885846-8ceed8f9-8839-427e-b0c2-8d166a27607c.png)
![QQ截图20221014233452](https://user-images.githubusercontent.com/111116375/195885865-3ae882b8-cf64-4176-b271-be94bb5d51ef.png)

**Comment by joeyHXD** [comment]
你这个应该是缺少hoshino的反并发插件？去git pull一下hoshino吧

**Comment by joeyHXD** [comment]
emmm...星乃那边也没有tool.py了好像...
![image](https://user-images.githubusercontent.com/68325229/195891382-ac5f1fc2-d720-4555-990b-c429a916c485.png)
我这边是这样的

**Comment by joeyHXD** [comment]
来，把这个插件装上，注意目录不太一样哦
https://github.com/lhhxxxxx/hoshino_tool.git

**Comment by XT-G3** [comment]
是，但是我找了这个tool下好了以后还是不行
![QQ截图20221015001924](https://user-images.githubusercontent.com/111116375/195895461-bc699586-bf8e-420c-873b-cd1548d67138.png)
![QQ截图20221015001952](https://user-images.githubusercontent.com/111116375/195895473-436c1623-865e-4fde-ad84-0bc4545aa85f.png)

**Comment by XT-G3** [comment]
我现在在找找那个eqa看看下下来会怎么样

**Comment by XT-G3** [comment]
这下一环套一环了，要怎么搞啊（
![QQ截图20221015003904](https://user-images.githubusercontent.com/111116375/195898054-7f0ff9e7-2325-46df-b22f-46df23bc43a3.png)

**Comment by joeyHXD** [comment]
> 这下一环套一环了，要怎么搞啊（ ![QQ截图20221015003904](https://user-images.githubusercontent.com/111116375/195898054-7f0ff9e7-2325-46df-b22f-46df23bc43a3.png)

这个是要`pip install retrying`吧

**Comment by joeyHXD** [comment]
eqa如果你没有的话，
![image](https://user-images.githubusercontent.com/68325229/195899732-51333dc0-c64b-49f6-a882-37a197dee351.png)
把这个改成eqa_db_dir = ""应该就行了

**Comment by joeyHXD** [comment]
加我qq吧，2241192063这个确实缝了一堆我也不知道还有什么依赖漏了
